name: WeChat-SendMessage

on:
  push:
    branches: [ main ]
    paths-ignore: 
      - 'README.md'
      - 'imgs/**'
  schedule:
    - cron: 30 4 * * *
  watch:
    types: [started]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout actions
    - uses: actions/checkout@v1

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
		
    - name: Update paper list
      run: python generate_tables.py
      env:
          SCKEY: ${{ secrets.SCKEY }}
          COOKIE: ${{ secrets.COOKIE }}

